### ISSUE TITLE
README example fails

### ISSUE THREAD

**Issue by 0xCoto** [mgm8/pyngham#20]
It appears that the example on the README fails to run:

```py
Traceback (most recent call last):
  File "/home/apostolos/Desktop/joss_review/test_example.py", line 1, in <module>
    from pyngham import PyNGHam
  File "/home/apostolos/.local/lib/python3.10/site-packages/pyngham/__init__.py", line 24, in <module>
    from pyngham.pyngham import PyNGHam
  File "/home/apostolos/.local/lib/python3.10/site-packages/pyngham/pyngham.py", line 25, in <module>
    from crc import CrcCalculator, Configuration
ImportError: cannot import name 'CrcCalculator' from 'crc' (/home/apostolos/.local/lib/python3.10/site-packages/crc.py)
```

**Comment by jbytecode** [comment]
Due to the JOSS submission: https://github.com/openjournals/joss-reviews/issues/4915

**Comment by mgm8** [comment]
This is because of a recent update in the [crc library](https://pypi.org/project/crc/). In version 3.0 they changed the structure of the library.

I fixed this in [25a60f9](https://github.com/mgm8/pyngham/commit/25a60f9c7f9ab8aba860a91ad79d0ae03f1218b9) and [a0dfd94](https://github.com/mgm8/pyngham/commit/a0dfd94df13f0ee5097aeca92c436ade2daccdee).

I will release a new version (v1.1) with these updates.

**Comment by 0xCoto** [comment]
Let me know when v1.1 is released.

**Comment by mgm8** [comment]
@0xCoto [v1.1 released](https://github.com/mgm8/pyngham/releases/tag/v1.1)
